spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: springcloud-dev
server:
  port: 5003
---
spring:
  profiles: test
  application: springcloud-test
server:
  port: 5002
